export const BoysTeamList = [
  "Dalhausser/Lucena",
  " Paulis/Satterfield",
  " Rosener/Cervantes",
  " Hiehle/Semo",
  " Deuchar/Haine",
  "Crabb/Gibb",
  " Mewhirter/Burik",
  " Caldwell/Meer",
  " Smallwood/Semo",
  " Guerreiro/Ashment",
  "Patterson/Budinger",
  " Vaught/Webber",
  " Ferrari/Mewhirter",
  " Tralka/McDonald",
  " Salfetnikov/Terekhin",
  "Casebeer/Schalk",
  " Roberts/Benesh",
  " Austin/Schultz",
  " Cronick/Semo",
  "Bomgren/Field",
  " Rosenthal/Cook",
  " Motter/Ospina",
  " Sutton/Keller",
  "Priddy/Santos",
  " Partain/Priima",
  " Muagututia/Jacobs",
  " lubliner/McBride",
  "Doherty/Evans",
  " Friend/Lotman",
  " Schwengel/Irvin",
  " Cox/Ellis",
  "Bourne/Crabb",
  " Kolinske/Beranek",
  " Lorenz/DiVenere",
  " Shipps/Jones",
  "Allen/Slick",
  " Hyden/Brunner",
  " Porter/Porter",
  " Fleming/Komar",
  "Drost/Frishman",
  " McKibbin/McKibbin",
  " Mayer/Shavit",
  " Shaffer/Fiers"
];

export const GirlsTeamList = [
  "Patterson/Budinger",
  " Vaught/Webber",
  " Ferrari/Mewhirter",
  " Tralka/McDonald",
  " Salfetnikov/Terekhin",
  "Casebeer/Schalk",
  " Roberts/Benesh",
  " Austin/Schultz",
  " Cronick/Semo",
  "Bomgren/Field",
  " Rosenthal/Cook",
  " Motter/Ospina",
  " Sutton/Keller",
  "Priddy/Santos",
  " Partain/Priima",
  " Muagututia/Jacobs",
  " lubliner/McBride",
  "Doherty/Evans",
  " Friend/Lotman",
  " Schwengel/Irvin",
  " Cox/Ellis",
  "Bourne/Crabb",
  " Kolinske/Beranek",
  " Lorenz/DiVenere",
  " Shipps/Jones",
  "Allen/Slick",
  " Hyden/Brunner",
  " Porter/Porter",
  " Fleming/Komar",
  "Drost/Frishman",
  " McKibbin/McKibbin",
  " Mayer/Shavit",
  " Shaffer/Fiers"
];
